# @maxfangx's nix packages and home-manager configs.
{
  # Pinned dependencies, generated by `npins`
  sources ? import ./npins,
  # Pinned nixpkgs source path
  nixpkgs ? sources.nixpkgs,
  # Pinned home-manager source path
  home-manager ? sources.home-manager,
  # The system packages will be built for
  system ? builtins.currentSystem,
  # Package set
  pkgs ? import nixpkgs {
    inherit system;
    config = {
      allowUnfree = true;
      android_sdk.accept_license = true;
    };
    overlays = [];
  },
  hm ? import home-manager { inherit pkgs; },
}:
rec {
  inherit hm pkgs sources;

  # Personal packages
  claude-code = pkgs.callPackage ./pkgs/claude-code {};
  omnara = pkgs.callPackage ./pkgs/omnara {};

  # home-manager configs
  homeConfigs = import ./home {
    inherit hm pkgs sources claude-code omnara;
  };
}
