# @maxfangx's nix packages and home-manager configs.
{
  # Pinned dependencies, generated by `npins`
  sources ? import ./npins,
  # Pinned nixpkgs source path
  nixpkgs ? sources.nixpkgs,
  # Pinned home-manager source path
  home-manager ? sources.home-manager,
  # The system packages will be built for
  system ? builtins.currentSystem,
  # Package set
  pkgs ? import nixpkgs {
    inherit system;
    config = {
      allowUnfree = true;
      android_sdk.accept_license = true;
    };
    overlays = [];
  },
  hm ? import home-manager { inherit pkgs; },
}:
rec {
  inherit hm pkgs sources;

  # Personal packages
  claude-code = pkgs.callPackage ./pkgs/claude-code {};
  codex = pkgs.callPackage ./pkgs/codex {};
  git-hunk = pkgs.callPackage ./pkgs/git-hunk {};
  jj = pkgs.callPackage ./pkgs/jj {};
  jj-hunk-tool = pkgs.callPackage ./pkgs/jj-hunk-tool {};
  omnara = pkgs.callPackage ./pkgs/omnara {};
  paseo = pkgs.callPackage ./pkgs/paseo {};
  rsync = pkgs.callPackage ./pkgs/rsync.nix {};

  # home-manager configs
  homeConfigs = import ./home {
    inherit hm pkgs sources claude-code codex git-hunk jj jj-hunk-tool omnara paseo rsync;
  };
}
